version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 14

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Berlin"

  - package-ecosystem: "opentofu"
    directory: "tf"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "Europe/Berlin"
    cooldown:
      default-days: 14
