name: CI
on:
  - push
  - pull_request
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Runs tests
        uses: ./.github/workflows/test.yml

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build project
        uses: ./.github/workflows/build.yml
